spring:
  application:
    name: POC - RocketMQ

logging:
  file: poc_rocketMq.log
  level:
    root: DEBUG

rocketMQConf:
  produceGroup: ${artifactId}
  topics:
    - topicName: topic1
      tags:
        - tag1
        - tag2
    - topicName: topic2
      tags:

